version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - gosec
    - misspell
    - unconvert
    - goconst
    - testifylint
    - usestdlibvars
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
    goconst:
      find-duplicates: true
      min-len: 5
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - wrapperFunc
        - hugeParam
        - unnamedResult
        - evalOrder
        - appendCombine
        - nestingReduce
