# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.36.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "988edfb10c1aa50e68c242f6671fba47ffe50f775276c5dfef140bbf4057f393"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "590399184850b8f88a46919d98863e9fe95377f0ed74a354c455cf42d8be468b"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "d44ee9c840e9e88a7672af193a229d826b0a609283baf51a533ac5f83ec16a25"
    end
  end

  caveats do
    "On first run, macOS may block the binary. To remove the quarantine attribute:"
    "  xattr -d com.apple.quarantine #{staged_path}/lazyworktree"
  end

  # No zap stanza required
end
