# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "0b7bfd108acae1e3bc6226c3f6b0c9b23e313bb015fc3b305da826c6b45c3f03"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "1d684156516d21a2949c0af94bdc95e440649969096eb6b214393728d5066563"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "e31af5d10cc30297c8c643b1b9dfb7f434218c7df7a5a6b7989ea5bb09d131c7"
    end
  end

  # No zap stanza required
end
