# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "f29e85bf3232eb06b0ce47e52cace76e830a3f3e3c0d23959668efb33fa98127"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "6427de7b4e9fb87487036e02a1f8372f7f827e00c0b5319d909fdc417fe29e01"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "29f4cec49efdd08c787db6986976fdd80b202ab7962d8dcc26bb950055b902ef"
    end
  end

  # No zap stanza required
end
